// Public header for the Greeter SHARED library.
#pragma once

#include <string>

// greeter_export.h is generated by CMake's GenerateExportHeader, wired up by
// cpp_library(... EXPORT_HEADER). Its directory is added to Greeter's PUBLIC include path, so
// both this library and its consumers can include it by name. It defines GREETER_EXPORT.
#include "greeter_export.h"

namespace greeter {

// GREETER_EXPORT marks this function for export from the shared library: it becomes
// __declspec(dllexport) while Greeter is being built and __declspec(dllimport) when a consumer
// (GreeterApp) links against it, and default visibility on GCC/Clang. This is what lets the
// executable resolve the symbol on every platform.
GREETER_EXPORT std::string greeting();

}  // namespace greeter
