# In-repo vcpkg overlay port for the Targets library.
#
# Targets is a scripts-only CMake library (no compiled runtime). This port drives the
# project's own root CMakeLists.txt through the vcpkg CMake helpers so it installs the
# EXACT SAME layout as `cmake --install` (a config generated by
# configure_package_config_file, plus the CMake modules under share/targets/cmake and a
# TargetsConfigVersion.cmake). That is the layout the published registry port produces,
# so this overlay can no longer diverge from it (see issue #2).
#
# Unlike the published registry port (which downloads a pinned release via
# vcpkg_from_github), this in-repo port builds from the local checkout, which is what you
# want when consuming it as a development overlay port (see docs/MIGRATION.md).

# Scripts-only port: it ships CMake modules under share/targets and installs no headers.
# Declare the missing include/ directory as intentional so vcpkg's post-build validation
# does not flag it (keeps the port green under --enforce-port-checks).
set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

# Build from the local checkout: this portfile lives at <repo>/ports/targets.
set(SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/../..")

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DTARGETS_BUILD_EXAMPLES=OFF
    -DTARGETS_BUILD_TESTS=OFF
)
vcpkg_cmake_install()

# Normalize the generated CMake package config (installed to share/targets by the root
# CMakeLists) and strip absolute paths.
vcpkg_cmake_config_fixup()

# Scripts-only package: there is no debug variant to ship.
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

# License (as copyright) and the usage hint.
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
file(INSTALL
  "${CMAKE_CURRENT_LIST_DIR}/usage"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
