# embed_binary(): turn binary files into a static library of C++ byte arrays.

include_guard(GLOBAL)

# For the shared _targets_check_args() argument validator.
get_filename_component(_TARGETS_UTILS_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_TARGETS_ROOT_DIR "${_TARGETS_UTILS_DIR}" PATH)
include("${_TARGETS_ROOT_DIR}/core/cpp_target.cmake")

# Create a static library holding the contents of binary files as C++ byte arrays.
#
# Each file yields a <identifier>.h / <identifier>.cpp pair declaring
# `extern const unsigned char <identifier>_data[]` and `extern const std::size_t
# <identifier>_size`, where the identifier is the file's name with every character C does not
# accept replaced. The generated directory is on the library's PUBLIC include path, so a
# consumer links the target and includes "<identifier>.h". Two files whose names produce the
# same identifier overwrite each other's generated sources.
#
# Arguments:
#   TARGET: Name of the library target to create (required).
#   FILES: The files to embed (required). A relative entry resolves against
#          CMAKE_CURRENT_SOURCE_DIR; each must exist at configure time.
#   NAMESPACE: C++ namespace the declarations go in (default: `embedded`). A `::` in it is
#              also folded into the header guard, with `_` in place of the separator.
#   OUTPUT_DIR: Directory the generated sources are written to (default:
#               CMAKE_CURRENT_BINARY_DIR/_embed_binary/<target>).
#
# The files are READ AT CONFIGURE TIME and their bytes written into the generated sources, so
# a changed input is not picked up until the next configure -- unlike a codegen rule driven by
# a custom command. Embedding is byte-for-byte, so the generated source is roughly six times
# the size of the input.
#
# FATAL_ERROR when TARGET or FILES is missing, an argument is unrecognized, or a named file
# does not exist.
#
# Example:
#   embed_binary(
#       TARGET EmbeddedAssets
#       FILES
#           assets/logo.png
#           assets/config.json
#       NAMESPACE MyApp::Assets
#   )
function(embed_binary)
  set(options)
  set(one_value_args
    TARGET
    NAMESPACE
    OUTPUT_DIR
  )
  set(multi_value_args FILES)

  cmake_parse_arguments(
    PARSE_ARGV 0
    args
    "${options}"
    "${one_value_args}"
    "${multi_value_args}")

  _targets_check_args("embed_binary"
    "${args_UNPARSED_ARGUMENTS}"
    "${args_KEYWORDS_MISSING_VALUES}"
    ${options} ${one_value_args} ${multi_value_args})

  if(NOT args_TARGET)
    message(FATAL_ERROR "embed_binary: TARGET argument is required")
  endif()

  if(NOT args_FILES)
    message(FATAL_ERROR "embed_binary: FILES argument is required")
  endif()

  if(NOT args_OUTPUT_DIR)
    set(args_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/_embed_binary/${args_TARGET}")
  endif()

  if(NOT args_NAMESPACE)
    set(args_NAMESPACE "embedded")
  endif()

  # The namespace reaches the header guard, where "::" is not spellable.
  string(REPLACE "::" "_" namespace_prefix "${args_NAMESPACE}")

  file(MAKE_DIRECTORY "${args_OUTPUT_DIR}")

  unset(generated_sources)
  unset(generated_headers)

  foreach(file_path ${args_FILES})
    cmake_path(IS_ABSOLUTE file_path is_absolute)
    if(NOT is_absolute)
      set(file_path "${CMAKE_CURRENT_SOURCE_DIR}/${file_path}")
    endif()

    if(NOT EXISTS "${file_path}")
      message(FATAL_ERROR "embed_binary: File does not exist: ${file_path}")
    endif()

    get_filename_component(filename "${file_path}" NAME)
    string(MAKE_C_IDENTIFIER "${filename}" var_name)

    set(output_header "${args_OUTPUT_DIR}/${var_name}.h")
    set(output_source "${args_OUTPUT_DIR}/${var_name}.cpp")

    # HEX is the only encoding file(READ) offers that survives arbitrary bytes; the loop below
    # turns it back into one 0x.. literal per byte, wrapped every 16 for readability.
    file(READ "${file_path}" file_contents HEX)

    string(LENGTH "${file_contents}" hex_length)
    math(EXPR data_length "${hex_length} / 2")

    set(array_data "")
    string(REGEX MATCHALL ".." hex_bytes "${file_contents}")
    list(LENGTH hex_bytes num_bytes)
    set(counter 0)
    foreach(byte ${hex_bytes})
      if(counter GREATER 0)
        string(APPEND array_data ", ")
      endif()
      if(counter GREATER 0)
        math(EXPR mod "${counter} % 16")
        if(mod EQUAL 0)
          string(APPEND array_data "\n    ")
        endif()
      endif()
      string(APPEND array_data "0x${byte}")
      math(EXPR counter "${counter} + 1")
    endforeach()

    file(WRITE "${output_header}"
"// Auto-generated by embed_binary
// Source file: ${filename}

#ifndef ${namespace_prefix}_${var_name}_H
#define ${namespace_prefix}_${var_name}_H

#include <cstddef>

namespace ${args_NAMESPACE} {

extern const unsigned char ${var_name}_data[];
extern const std::size_t ${var_name}_size;

} // namespace ${args_NAMESPACE}

#endif // ${namespace_prefix}_${var_name}_H
")

    file(WRITE "${output_source}"
"// Auto-generated by embed_binary
// Source file: ${filename}

#include \"${var_name}.h\"

namespace ${args_NAMESPACE} {

const unsigned char ${var_name}_data[] = {
    ${array_data}
};

const std::size_t ${var_name}_size = ${data_length};

} // namespace ${args_NAMESPACE}
")

    list(APPEND generated_sources "${output_source}")
    list(APPEND generated_headers "${output_header}")
  endforeach()

  add_library(${args_TARGET} STATIC
    ${generated_sources}
    ${generated_headers}
  )

  _targets_apply_common_target_defaults(${args_TARGET})

  target_include_directories(${args_TARGET}
    PUBLIC
      "$<BUILD_INTERFACE:${args_OUTPUT_DIR}>"
  )

  source_group("Generated Files" FILES ${generated_sources} ${generated_headers})

  list(LENGTH args_FILES num_files)
  message(STATUS "embed_binary: Created target ${args_TARGET} with ${num_files} embedded files")
endfunction()
